### PR TITLE
Disable save button if not all fields visited or not all fields valid

### LINKED ISSUE #524: [Clinical Services] The system is permiting to save clincal services without required fields
Actual Results
--
The system is saving the clinical services even when not all the steps are visited and required fields not filled. 

Expected results
--
Should not permit to save if not all the steps are visited or required fields are not filled.

Steps to reproduce
--
Login > Any module with clinical service > Serviço Clínico > Adicionar > Click on the last step > Próximo > Confirmar

Screenshot/Attachment (Optional)
--
A visual description of the unexpected behaviour.
image

### PR DESCRIPTION
**Pull request by ynurmahomed**
Fixes #524.

### CODE REVIEW

**Comment by valvijo** [comment]
Almost, just need to prevent save with validation errors.
image

**Comment by ynurmahomed** [comment]
@valvijo

**Comment by ynurmahomed** [comment]
@valvijo fixed.

**Comment by ynurmahomed** [comment]
@valvijo

**Comment by valvijo** [comment]
Excellent!

**Pull request merged**
