### PR TITLE
EPCT-5 Not working drug refill action

### PR DESCRIPTION
**Pull request by ynurmahomed**
* Handle first time arv prescription

### CODE REVIEW

**Comment by ynurmahomed** [comment]
@Guimino updated.

**Comment by Guimino** [comment]
3.  When I change the regimen of an ARV item (in refill or adding an item) the List of the drugs is not changed for the  drugs of the  new selected regimen

**Comment by ynurmahomed** [comment]
@Guimino please review again.

**Comment by Guimino** [comment]
Merged #696

**Pull request merged**
