### PR TITLE
Date filter for FILA report

### PR DESCRIPTION
**Pull request by ynurmahomed**
@valvijo I was having trouble using angular-datepicker so I ended up using the datepicker from angular-bootstrap.
Somehow my earlier commits got lost after the last merge. The one that needs review is 44118dc.

### CODE REVIEW

**Comment by ynurmahomed** [comment]
Here is some mock [data](http://www.mockaroo.com/fed674a0).

**Comment by larslemos** [comment]
@valvijo "angular-datepicker" stoped being maintained since 2015.
The datepicker from "angular-bootstrap" is being supported by the community and belongs to the same angular ui repo

**Comment by ynurmahomed** [comment]
@valvijo I've implemented the filter by year. Is it OK to merge?

**Comment by larslemos** [comment]
@valvijo I proposed @ynurmahomed  to change the "common.patient" due to the Unit test that were failing since the once the module "registration" was being loaded for a service that had to many and unrelated dependencies for the functions being tested on the report only needed "'bahmni.common.appFramework".

**Pull request merged**
