### PR TITLE
Simplified prescription

### PR DESCRIPTION
**Pull request by valvijo**
**Current changes**
- Prescription drugs field is a typeahead search
- Prescription item was changed from concept to drug
- Drug types (ARV, Others) are identified behind the scenes.
- The list Drug Prescribed displays only past and active prescriptions/orders
- Drug Orders and Obs are encapsulated in the same encounter and posted in one transaction. `encounter {orders: myOrders, obs: myObs}`. Both retrospective and pharmacy app are supported and no convert adapter is needed.

**Missing changes**
- Prophylaxis type of drug is not contemplated
- Frequency  should be captured from `order_frequency` and swapped with `concept` for display
- Map drugs with regimens and therapeutic lines

### CODE REVIEW

**Comment by valvijo** [comment]
For quick test use the drugs:
- ARV: Triomune-40, d4T-30, d4T-40 or DDI 125
- Non ARV: DDI 200

**Comment by ningosi** [comment]
Seems some checks are not passing @valvijo

**Comment by valvijo** [comment]
Yes @ningosi this is codacy suggesting that a function has too many parameters `function ($q, $http, $filter, $scope, $rootScope, $stateParams, encounterService,`. I guess this is because a particular controller don't follow the [guidelines](https://github.com/johnpapa/angular-styleguide) we have agreed on, and that is because we didn't yet rewrite our code to follow that.

**Comment by ningosi** [comment]
@valvijo so this error of too many parameters passed if merged in will result into the breakage of the entire code base? How many should be maximum? Do we have some that are not applied in this method so that they can be trimmed?

**Comment by valvijo** [comment]
No it won't break anything, this is not a syntax or semantic error that can cause build, deploy or runtime issues, this is just a code guideline check that we set in codacy. I don't think that having too many parameters is the issue, but the way the function is written doesn't meet the guidelines. Two options, we can either ignore it and go ahead or rewrite the controller to meet the guidelines. We will do the second anyway so we have to decide if we want to do it now or letter considering time. What do you think?

**Comment by ningosi** [comment]
@valvijo let us merge and clean up later to meet the guidelines

**Pull request merged**
