### PR TITLE
Add Prescription provider field to prescription form

### PR DESCRIPTION
**Pull request by ynurmahomed**

### CODE REVIEW

**Comment by ynurmahomed** [comment]
[1.0.1_32 Feature: Add provider field to prescription form [5]](https://trello.com/c/i9ADsdIV/89-10132-feature-add-provider-field-to-prescription-form-5)

**Comment by valvijo** [comment]
The provider field should not be visible in clinical prescriptions and the encounter provider is set in the background for the logged user. The field is visible for IF and should be mandatory, the encounter provider is the  field value.

**Comment by ynurmahomed** [comment]
Ok. updates coming.

**Comment by ynurmahomed** [comment]
Should prescription date field be visible in prescription for clinical module?

**Comment by ynurmahomed** [comment]
@valvijo

**Comment by valvijo** [comment]
This is what happen when I try to cancel a prescription item
image

**Comment by ynurmahomed** [comment]
the validation was already there i just changed the events, what should happen?

**Comment by valvijo** [comment]
The typeahead is not filtering while typing as it's suppose to do, it lists all the providers and bold the one I want.
image

**Comment by valvijo** [comment]
This is what was there before:
image

**Comment by ynurmahomed** [comment]
should i revert?

**Comment by valvijo** [comment]
There are 2 options: (1) Revert and be consistent with the way other modal dialogs present messages, (2) Keep this one and present with an intuitive message, but will also have to change existing dialogs to be consistent. Either way if fine with me, you decide

**Comment by valvijo** [comment]
Also the labels are not ok for clinical prescription

**Pull request merged**
