### PR TITLE
Fix checkin controller

### LINKED ISSUE #265: The system should prevent the users from refreshing the pages

### LINKED ISSUE #281: [Vitals] Add Vitals not working
When click on + button system shows white screen on tablet and PC. Sometimes on PC returns to search page.

Scenario:
================
link: http://dev.esaude.org/
User: admin/eSaude123
Module: Vitals
Patient: Malocy

### PR DESCRIPTION
**Pull request by Guimino**
BugFix on Refreshing patient Detail specifically in Visit and Checkin controller
Fix #265 
Fix #281

### CODE REVIEW

**Comment by ynurmahomed** [comment]
[1.3.0_10 Bug: The system should prevent the users from refreshing the pages](https://trello.com/c/mh8gSu25/237-13010-bug-the-system-should-prevent-the-users-from-refreshing-the-pages)

**Comment by valvijo** [comment]
@Guimino is this failing check being fixed?

**Comment by ynurmahomed** [comment]
@valvijo I'm making adjustments to this one.

**Comment by ynurmahomed** [comment]
[1.3.0_11 Bug: [Vitals] Add Vitals not working](https://trello.com/c/NQsUGwsM/240-13011-bug-vitals-add-vitals-not-working)

**Pull request merged**
