### PR TITLE
Change method and constant names to align with eSaude Pharmacy API

### PR DESCRIPTION
**Pull request by ynurmahomed**

### CODE REVIEW

**Comment by ynurmahomed** [comment]
@valvijo I have some concerns about prescription endpoint. 

When we call ```/prescription?patient=<patientUUID>``` for a patient with 1 prescription with 2 drugs prescribed we get back a list with 2 objects containing each of the drugs.

Is this really how it is supposed to work or is it a bug in [pharmacy API](https://github.com/esaude/openmrs-module-pharmacyapi/issues/new)?

**Comment by valvijo** [comment]
@ynurmahomed a prescription items should come with more information that the drug it represents, e.g. dose, dosing units, duration, duration units, frequency, etc. I guess the purpose of each object you see is to wrap the drug with all the associated attributes. I'm not sure of what the object structure is but it's suppose to be a drug_order + ARV specific attributes, Am I right @Guimino? Please let me know if this answers your question

**Comment by ynurmahomed** [comment]
@valvijo and @Guimino there are 2 problems I have with this endpoint:

* Resource representation, I was expecting the prescription to be something like this:
```
{
    ...
    drugs: [
    ]
}
```

* Semantics, it returns only prescriptions that have not been entirely dispensed. We need to get all prescriptions regardless of dispensation status for the FILA report. The way it is right now the prescription calendar on FILA report will only be correct sometimes (when prescriptions have not been entirely dispensed).

**Comment by valvijo** [comment]
@ynurmahomed  what's the current prescription object structure?

**Comment by Guimino** [comment]
Hi @valvijo <https://github.com/valvijo> and @ynurmahomed
<https://github.com/ynurmahomed>,  the current endpoint  were developed for
lookup for prescription not dispensed and not entirely dispensed. this is
the preconditional  for dispensation.
If necessary, we can create another logic within the  prescription endpoint
to feed the FILA report.

About the structure of the resource representation, look below:

{
   uuid,
   *drugOrder *(That has an one-to-one relationship with drugOrder  and
DrugOrder has a Drug attribute),
  dosingInstructions,
  provider,
  prescriptionDate,
  conceptParentUuid,
  drugToPickUp,
  drugPickedUp,
  drugRegime
}

So this resource needs to be refactored, and  as soon as possible I'll
refactory.

2017-06-27 9:52 GMT+02:00 Valério João <notifications@github.com>:

**Comment by ynurmahomed** [comment]
@valvijo can this PR be merged?

**Pull request merged**
