### PR TITLE
Validate test result ranges

### PR DESCRIPTION
**Pull request by ynurmahomed**
[Validate ranges & display units](https://trello.com/c/DMnH5jIu/59-validate-ranges-display-units)

### CODE REVIEW

**Comment by ynurmahomed** [comment]
[Validate ranges & display units](https://trello.com/c/DMnH5jIu/59-validate-ranges-display-units)

**Comment by ningosi** [comment]
I am yet to finish fixing the minimum and maximum units for this to be tested against

**Comment by valvijo** [comment]
Thank you. Please notify me when you'r done so that I can close this.

**Comment by valvijo** [comment]
@ningosi any update on the concepts needed here?

**Pull request merged**
